server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todotaskdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  platform: org.hibernate.dialect.H2Dialect

  quartz:
    job-store-type: jdbc

  h2:
    console:
      enabled=: true


  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    properties:
        hibernate:
          format_sql: false

